name = "nse-live-terminal"
main = "worker.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SCREENER_KV"
id = "8731d7cd5c76462f9e9b8e0778c06364"
